services:
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "home-library-db"
    container_name: "db"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:${PGDATA}
    ports:
      - "5442:5432"
    restart: on-failure
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    image: "home-library-app"
    container_name: "app"
    depends_on:
      - db
    environment:
      - DB_URL=db
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
    ports:
      - "80:8080"
volumes:
  db:
    driver: local
